mojaloop/sdk-scheme-adapter

src/config.js
src/package.json

2. bump version of standard components to fix accept headers on PUT requests

1. fix cant find jws pub key for mojaoop-sdk error

---

src/inboundApi/api.yaml
src/index.js
src/lib/validate/index.js

2. send mojaloop api spec errors for validation errors
3. minor linting fix.

1. fix party id type path parameter in mojaloop api swagger spec

---

docs/dfspInboundApi.yaml

This file has all recent changes: dateOfBirth replacing timestamp, editorial changes, and Apache license info. This fixes the recent mixup around this file.

dateOfBirth + editorial + license

---

src/inboundApi/handlers.js
src/lib/model/outboundModel.js

mowdev-1135 handle parties, quotes and transfers error callback endpoints

---

src/lib/model/lib/shared/index.js

Updated code to remove quoteId being part of the response being sent in PUT /quotes/{ID}

Bug fix for 1551

---

.circleci/config.yml
Dockerfile
src/package-lock.json
src/package.json

* Added missing dependency of `@modusbox/mojaloop-sdk-standard-compon
* Replaced with an up to date version of `package-lock.json`
* Replaced `npm install` with `npm ci` in circleci config.

Fixed issues with missing packages

---

src/outboundApi/api.yaml
src/outboundApi/handlers.js
src/package.json

update outbound api swagger to allow party acceptance as well as quote acceptance

update outbound api swagger

---

src/package.json

Make use of recent fixes in sdk-standard-components

bump sdk-standard-components version

---

src/config.js
src/lib/model/outboundModel.js
src/local.env
src/package.json
src/test/unit/config.test.js
src/test/unit/lib/model/outboundModel.test.js

add transfer payee fsp override config flag to handle forex redirect usecase

transfer payee fsp override config flag to handle forex redirect

---

src/outboundApi/api.yaml

MP-601 update outbound scheme adapter api swagger to reflect recent changes and more fully describe the model

MP-601 update outbound scheme adapter api swagger

---

Dockerfile
src/lib/model/OutboundTransfersModel.js
src/lib/model/common.js
src/test/unit/lib/model/OutboundTransfersModel.test.js

MP-643 fix circular references in returned errors from outbound transfers model

MP-643 fix circular references in returned errors

---

src/lib/model/OutboundTransfersModel.js
src/test/unit/lib/model/OutboundTransfersModel.test.js

MP-728,MOWDEV-3218 use transferAmount from quote response in prepare, not amount from initial request

MP-728,MOWDEV-3218 use transferAmount from quote response in prepare

---

.circleci/config.yml
Dockerfile
src/package-lock.json
src/package.json

update dockerfile to cater for node-gyp and node-rdkafka library

changed to older node version because of node-gyp and node-rdkafka

---

src/lib/model/OutboundTransfersModel.js

Prevents loss of quoteId if error occurs during send.

store quoteId in state before sending quote request

---

src/InboundServer/middlewares.js
src/lib/model/lib/requests/backendRequests.js

1. log request before jws validation to enable debugging of jws failures.
2. use keep alive tcp connections to backend

debugging and performance tweaks

---

docs/dfspInboundApi.yaml
src/InboundServer/api.yaml
src/OutboundServer/api.yaml
src/lib/model/lib/shared/index.js
src/test/unit/api/transfers/data/putPartiesBody.json
src/test/unit/data/putPartiesBody.json

Slightly confused here 
docs/dfspInboundApi.yaml - Api for calls from dfsp backend?
src/InboundServer/api.yaml - Api for icalls from switch?
src/OutboundServer/api.yaml - Api for calls sent to switch?
@bushjames @lewisdaly

 Updated library to adapt dfsp party accounts.

---

src/OutboundServer/handlers.js
src/test/unit/outboundApi/handlers.test.js

fixing test for happy flow on the outbound server

test: fix broken test

---

src/InboundServer/middlewares.js
src/config.js
src/lib/model/InboundTransfersModel.js
src/lib/model/lib/requests/backendRequests.js
src/lib/model/lib/shared/index.js
src/package.json
src/test/unit/lib/model/InboundTransfersModel.test.js

- Fixed misspelt environment variable index
- Fixed bugs related to bulk transfers

#1386: Bug fixes

---

src/package.json

- Update sdk-standard-components to fix issue with JWS signing for bulkTransfers

#1386: Update sdk-standard-component

---

package-lock.json
src/lib/model/InboundThirdpartyTransactionModel.js
src/lib/model/InboundTransfersModel.js
src/package.json

fix problems how the error are handled by InboudServer state machines

fix: the way how errors are handled at InboundServer

---

src/package-lock.json
src/package.json

Use @mojaloop/sdk-standard-components v11.5.2

---

src/InboundServer/handlers.js
src/InboundServer/index.js
src/InboundServer/middlewares.js
src/OutboundServer/handlers.js
src/OutboundServer/index.js
src/TestServer/index.js
src/config.js
src/index.js
src/lib/model/InboundTransfersModel.js
src/lib/model/OutboundRequestToPayModel.js
src/lib/model/OutboundTransfersModel.js
src/package-lock.json
src/package.json
src/test/unit/InboundServer.test.js
src/test/unit/TestServer.test.js
src/test/unit/config.test.js
src/test/unit/data/defaultConfig.json
src/test/unit/lib/model/AccountsModel.test.js
src/test/unit/lib/model/OutboundBulkQuotesModel.test.js
src/test/unit/lib/model/OutboundBulkTransfersModel.test.js
src/test/unit/lib/model/OutboundRequestToPayModel.test.js
src/test/unit/lib/model/OutboundRequestToPayTransferModel.test.js
src/test/unit/lib/model/OutboundTransfersModel.test.js
src/test/unit/lib/model/data/defaultConfig.json

Also moved inbound caching into middleware

Partial config restructure for clearer API

---

src/InboundServer/index.js
src/OutboundServer/index.js
src/TestServer/index.js
src/index.js
src/lib/cache/cache.js
src/package-lock.json
src/package.json
src/test/unit/TestServer.test.js
src/test/unit/api/utils.js

This reduces the API surface required for a cache implementation to the minimum necessary

Extract cache connection logic from servers

---

src/OutboundServer/handlers.js
src/lib/model/OutboundAuthorizationsModel.js
src/lib/model/OutboundRequestToPayTransferModel.js
src/lib/model/lib/requests/backendRequests.js
src/test/unit/lib/model/OutboundAuthorizationsModel.test.js

POC: extend OutboundRequestToPayTransferModel to work in PISP mode and kick off a call POST /authorization after receiving the quote
fix some small bugs

feat: 1671 kick off post authorization

---

.circleci/config.yml
Dockerfile
src/InboundServer/index.js
src/InboundServer/middlewares.js
src/OutboundServer/handlers.js
src/OutboundServer/index.js
src/config.js
src/index.js
src/lib/model/InboundTransfersModel.js
src/lib/model/OutboundBulkQuotesModel.js
src/lib/model/OutboundTransfersModel.js
src/package-lock.json
src/package.json
src/test/unit/InboundServer.test.js
src/test/unit/config.test.js
src/test/unit/data/defaultConfig.json
src/test/unit/lib/model/AccountsModel.test.js
src/test/unit/lib/model/OutboundBulkQuotesModel.test.js
src/test/unit/lib/model/OutboundBulkTransfersModel.test.js
src/test/unit/lib/model/OutboundRequestToPayModel.test.js
src/test/unit/lib/model/OutboundRequestToPayTransferModel.test.js
src/test/unit/lib/model/OutboundTransfersModel.test.js
src/test/unit/lib/model/data/defaultConfig.json

More notes:
- additionally, made some config modifications to improve readability of config
- also, updated the node version in use
- no environment variable changes, no API changes, hence only a patch version bump
PR is draft pending merge and release of https://github.com/mojaloop/sdk-standard-components/pull/125. Once that's merged and released, it'll be necessary to run `npm install` to update dependencies and version in `package-lock.json`, commit that to this repo, then merge and release.

Fix broken outbound TLS config

---

.circleci/config.yml
.gitignore
src/InboundServer/api.yaml
src/InboundServer/handlers.js
src/OutboundServer/api.yaml
src/OutboundServer/handlers.js
src/babel.config.js
src/lib/model/OutboundRequestToPayModel.js
src/lib/model/OutboundRequestToPayTransferModel.js
src/lib/model/OutboundTransfersModel.js
src/lib/model/PartiesModel.js
src/lib/model/common/BackendError.js
src/lib/model/common/PersistentStateMachine.js
src/lib/model/common/index.js
src/lib/model/index.js
src/package-lock.json
src/package.json
src/test/unit/lib/model/OutboundRequestToPayModel.test.js
src/test/unit/lib/model/OutboundTransfersModel.test.js
src/test/unit/lib/model/PartiesModel.test.js
src/test/unit/lib/model/common/PersistentStateMachine.test.js
src/test/unit/mockLogger.js
src/test/unit/outboundApi/data/mockGetPartiesError.json
src/test/unit/outboundApi/handlers.test.js

Implementing get /parties @ Outbound interface

feat: 1991 get parties

---

src/InboundServer/handlers.js
src/lib/model/PartiesModel.js
src/lib/model/lib/shared/deferredJob.js
src/lib/model/lib/shared/index.js
src/package-lock.json
src/package.json
src/test/unit/api/transfers/transfers.test.js
src/test/unit/lib/model/PartiesModel.test.js
src/test/unit/lib/model/data/defaultConfig.json

introduce of `defferedJob` module to handle in a consistent way async to sync the call transformation

feat: 1991 get parties timeout

---

src/InboundServer/handlers.js
src/OutboundServer/handlers.js
src/lib/model/Async2SyncModel.js
src/lib/model/OutboundRequestToPayModel.js
src/lib/model/OutboundRequestToPayTransferModel.js
src/lib/model/OutboundTransfersModel.js
src/lib/model/PartiesModel.js
src/package-lock.json
src/package.json
src/test/unit/lib/model/OutboundRequestToPayModel.test.js
src/test/unit/lib/model/OutboundTransfersModel.test.js
src/test/unit/lib/model/PartiesModel.test.js
src/test/unit/outboundApi/handlers.test.js

- Async2SyncModel generator
- generate PartiesModel

feat: 1991 generic async2sync

---

README.md
package-lock.json
src/InboundServer/api.yaml
src/InboundServer/api_template.yaml
src/package.json

All those nice `x-examples` get lost. I will add them to the paths on `api-snippets`, update the library here and rebuild the inteface at a later PR.

chore: template inbound interface with api-snippets

---

.circleci/config.yml

chore: fix npm command

---

src/package-lock.json
src/package.json

- Fix for 'Error: Cannot find module 'js-yaml''

fix(2151): helm-release-v12.1.0

---

src/lib/model/OutboundBulkQuotesModel.js
src/lib/model/OutboundBulkTransfersModel.js
src/lib/model/OutboundRequestToPayTransferModel.js
src/lib/model/OutboundTransfersModel.js
test/unit/lib/model/OutboundBulkQuotesModel.test.js
test/unit/lib/model/OutboundBulkTransfersModel.test.js
test/unit/lib/model/OutboundTransfersModel.test.js

Forgot to update the error handling with the new handler publishing data structure.

fix: reformat error information response

---

docs/design-bulk-transfers.md

feat: added auto accept party and quotes

feat: added auto accept party and quotes

---

README.md

- updated readme to include docker-pulls

chore: updates to readme for header badges [skip ci]

---

modules/api-svc/src/BackendEventHandler/handlers/sdk-outbound-bulk-accept-party-info-requested.js
modules/api-svc/src/BackendEventHandler/handlers/sdk-outbound-bulk-accept-quote-requested.js
modules/api-svc/src/FSPIOPEventHandler/handlers/bulk-quotes-requested.js
modules/api-svc/src/FSPIOPEventHandler/handlers/party-info-requested.js
modules/api-svc/src/FSPIOPEventHandler/index.js
modules/api-svc/src/index.js

fix([mojaloop/2809](https://github.com/mojaloop/project/issues/2809)): some api-svc issues

fix(mojaloop/2809): api-svc issues

---

modules/api-svc/package.json
modules/api-svc/src/BackendEventHandler/index.js
modules/api-svc/src/FSPIOPEventHandler/handlers/bulk-quotes-requested.js
modules/api-svc/src/FSPIOPEventHandler/handlers/party-info-requested.js
modules/api-svc/src/index.js
modules/outbound-command-event-handler/package.json
modules/outbound-domain-event-handler/package.json
package.json
yarn.lock

fix([mojaloop/2809](https://github.com/mojaloop/project/issues/2809)): some more issues with api-svc

fix(mojaloop/2809): some more issues

---

modules/api-svc/src/FSPIOPEventHandler/handlers/party-info-requested.js
modules/outbound-command-event-handler/package.json
modules/outbound-command-event-handler/src/domain/bulk_transaction_agg/handlers/process_sdk_outbound_bulk_party_info_request_complete.ts
modules/outbound-domain-event-handler/package.json
modules/private-shared-lib/package.json
package.json
yarn.lock

fix([mojaloop/2809](https://github.com/mojaloop/project/issues/2809)): individual transfer results is empty

fix(mojaloop/2809): individual transfer results is empty

---

modules/api-svc/package.json
modules/api-svc/src/OutboundServer/handlers.js
modules/outbound-command-event-handler/package.json
modules/outbound-domain-event-handler/package.json
modules/private-shared-lib/package.json
package.json
yarn.lock

fix POST /bulkTransactions http status code

fix: post bulk tx status code

---

docs/design-bulk-transfers/outbound-sequence.md
modules/outbound-command-event-handler/src/domain/bulk_transaction_agg/handlers/process_sdk_outbound_bulk_party_info_request.ts

send PartyInfoCallbackReceivedDmEvt if party info exists

fix: party lookup flow if party info exists

---

modules/api-svc/package.json
modules/api-svc/project.json
modules/outbound-command-event-handler/project.json
modules/outbound-domain-event-handler/project.json
nx.json
package.json
yarn.lock

Merge https://github.com/mojaloop/sdk-scheme-adapter/pull/393 into mvp/bulk-sdk

fix: ci build order

---

modules/api-svc/package.json
modules/api-svc/src/index.js
yarn.lock

fix: unit tests

---

modules/api-svc/src/lib/model/lib/shared.js
package.json
yarn.lock

- Fix issue with external to internal mapping.

fix: correct internal/external bulk quote convert function

---

modules/api-svc/package.json
modules/outbound-command-event-handler/package.json
modules/outbound-domain-event-handler/package.json
modules/private-shared-lib/package.json
package.json
test/func/config/ml-testing-toolkit/spec_files/api_definitions/mojaloop_simulator_sim_1.4/api_spec.yaml
yarn.lock

- Remove maxItems on component used in put /bulkTransactions individualTransferResults

chore: remove max items from put bulkTransactions

---

CHANGELOG.md

- added missing maintenance fix for nx 16 to changelog

docs: update CHANGELOG.md [skip ci]

---

modules/api-svc/src/lib/model/InboundTransfersModel.js

- Add a debug log to check the data being stored

chore: add log statements for debugging
