mojaloop/sdk-scheme-adapter

- src/__mocks__/@mojaloop/sdk-standard-components.js
- src/lib/model/outboundModel.js
- src/test/unit/outboundModel.test.js
1. fix missing ILP verification on outbound model
2. ensure outbound model tests use dummy environment rather than process.env to try to avoid clash with config module tests
> fix missing ILP verification on outbound model and enhance tests

- src/outboundApi/api.yaml
adding additional party identifier types from mojaloop api spec to allow testing of oracle developments
> adding additional party identifier types from mojaloop api spec

- Dockerfile
koa2-oauth-server module apparently needs git binary to npm install.
> Add git to docker image to allow npm install of oauth server component

- docs/dfspInboundApi.yaml
- src/lib/model/lib/requests/common.js
- src/lib/model/outboundModel.js
- src/outboundApi/handlers.js
- src/package.json
- src/test/__mocks__/@internal/cache.js
- src/test/unit/inboundApi/handlers.test.js
- src/test/unit/lib/model/outboundModel.test.js
- src/test/unit/outboundApi/handlers.test.js
If mojaloop errors are returned from the peer during synchronous outbound transfers the mojaloop error body should be included in the synchronous backend error response.
> MP-626 pass outbound model mojaloop errors back to caller

- src/package.json
Use latest sdk standard components version to get token refresh TLS credentials update.
> MP-805: use latest sdk standard components version

- src/lib/model/AccountsModel.js
- src/lib/model/OutboundTransfersModel.js
Missing await when making cache subscription can cause call to unsubscribe before subscribe has completed.
> fix missing await

- src/OutboundServer/handlers.js
- src/config.js
- src/package.json
- src/test/unit/config.test.js
- src/test/unit/outboundApi/data/mockError.json
- src/test/unit/outboundApi/handlers.test.js
MP-1261 add config to allow an extensionList item in a mojaloop error callback to be the source of statusCode in synchronous backend error response.
> MP-1261 error extensionList as source of error body statusCode property

- src/OutboundServer/handlers.js
- src/package.json
- src/test/unit/outboundApi/data/mockError.json
Extension list structure was incorrect in outbound model error handling code. This change fixes it.
> fix extension list structure in outbound handlers error handling

- .circleci/config.yml
- .dockerignore
- Dockerfile
- docker-compose.yml
- src/.env.example
- src/InboundServer/api.yaml
- src/InboundServer/handlers.js
- src/TestServer/api.yaml
- src/TestServer/handlers.js
- src/TestServer/index.js
- src/config.js
- src/index.js
- src/test/unit/TestServer.test.js
- src/test/unit/data/defaultConfig.json
A couple of other changes in this PR (although they probably shouldn't be, but I can't be bothered moving them):
- Dockerfile modified to cache node modules and avoid npm install every build
- Labels added to Dockerfile
- Added `.dockerignore` file to reduce docker build context size and avoid pollution by `node_modules`
Before merging, please review this:
https://github.com/msk-/sdk-scheme-adapter/pull/1
Additionally, it looks like the integration tests are not passing- was that the case previously? Is it because I changed the `npm install` command in the Dockerfile to `npm install --production`? I would have _guessed_ not, but I guess it's possible `npm prune --production` doesn't do what it says it does.
> Moved "test" API to a different server.

- src/OutboundServer/index.js
- src/lib/model/ProxyModel/index.js
- src/package.json
- src/test/unit/api/proxy/proxy.test.js
strip any base path off peerEndpoint config setting when proxying requests
> strip any base path off peerEndpoint config when proxying

- docker-compose.integration.yml
- src/config.js
- src/index.js
- src/package.json
`ENABLE_TEST_FEATURES` and `ENABLE_TEST_SERVER` are codependent config options, so I've replaced one with the other.
> Exposed log transports to config

- src/lib/model/lib/requests/common.js
- src/package.json
Recently introduced request library returns already parsed JSON response by default.
> Do not parse already processed JSON response.

- src/config.js
- src/package.json
Previously it was ALS_ENDPOINT. Somehow it is changed to ALS_ENDPOINT_HOST which is not referenced in any file other than config.js.
So reverting this name back to previous one.
> Renamed ALS_ENDPOINT_HOST to ALS_ENDPOINT

- src/lib/model/InboundTransfersModel.js
- src/package.json
- src/test/unit/lib/model/InboundTransfersModel.test.js
This PR does not contain a regression test for the functionality that has been changed because
1. It's not possible to write a unit test that isn't tied to a specific implementation of the request library used. To avoid the requirement of actually making an HTTP request, we would have to mock the request library used, in which case, we would have to match its API. A unit test mocking the request library but hoping to detect a regression that occurs when the request library API changes has a maintenance cost but no value.
2. The request library used is not expected to change rapidly.
I've fixed the package version for `sdk-standard-components` because `10.6.0` has a bug (missing file) which will prevent anyone from using it.
In further support of this, a (formatted some) log from the …
> requests now respond with .data instead of .body

- src/lib/model/InboundTransfersModel.js
- src/test/unit/lib/model/InboundTransfersModel.test.js
Related to #182, no longer need to parse response data as it's done here:
https://github.com/mojaloop/sdk-standard-components/blob/3ef2e57192fcb67f2ad54564df493d6f47a9fef7/src/lib/request.js#L65
> Do not JSON parse already-parsed response data

- src/InboundServer/handlers.js
- src/TestServer/index.js
- src/lib/cache/cache.js
- src/package.json
- src/test/unit/TestServer.test.js
- src/test/unit/data/defaultConfig.json
Currently a vast range of tests that use the test server do something like this:
1. initiate some action in the switch
2. wait some predetermined time, `w`
3. using `/callbacks` or `/requests`, verify whether the action was completed as expected
The problem arises at (2). If `w` is too short, the test will likely fail. If `w` is too long, the test will take longer than necessary. This is exacerbated by environmental differences. To take two extremes: running on a 1000 processor, 1000TB cluster `w` will be very different to a cluster comprised of a handful of Raspberry Pis. The large cluster will wait _far longer_ than it needs to. The small cluster might attempt step (3) before the action has completed, causing a false negative test result.
Moreover, in order to define `w` for a given …
> Websocket API for test server

- docs/dfspInboundApi.yaml
- src/InboundServer/api.yaml
- src/OutboundServer/api.yaml
- src/package.json
Adding XTS and XXX test currencies to enable testing on production environments without using live currencies.
> Add ISO-4217 test currencies to enable production testing scenarios.

- src/InboundServer/handlers.js
- src/InboundServer/index.js
- src/OutboundServer/handlers.js
- src/OutboundServer/index.js
- src/config.js
- src/index.js
- src/lib/model/AccountsModel.js
- src/lib/model/InboundTransfersModel.js
- src/lib/model/OutboundBulkQuotesModel.js
- src/lib/model/OutboundBulkTransfersModel.js
- src/lib/model/OutboundRequestToPayModel.js
- src/lib/model/OutboundRequestToPayTransferModel.js
- src/lib/model/OutboundTransfersModel.js
- src/package-lock.json
- src/package.json
- src/test/unit/data/defaultConfig.json
- src/test/unit/index.test.js
- src/test/unit/lib/model/data/defaultConfig.json
Two changes:
1. When a request fails with a 401, the new environment variable `WSO2_AUTH_FAILURE_REQUEST_RETRIES` will now allow the SDK to attempt to retrieve a new token, then retry the request, if WSO2 auth is enabled.
2. When WSO2 token retrieval fails, instead of failing silently, which has happened since the change of base request library from `request-promise` to `@mojaloop/sdk-standard-components/src/lib/request.js`, an error will now propagate to the top level (and crash the SDK)
> Incorporated new sdk-standard-components functionality into SDK

- src/lib/model/OutboundAuthorizationsModel.js
- src/test/unit/lib/model/OutboundAuthorizationsModel.test.js
- src/test/unit/lib/model/OutboundThirdpartyTransactionModel.test.js
- src/test/unit/lib/model/common/PersistentStateMachine.test.js
Yes you were correct Pawel. `then` runs after the test is finished.
- Changed to `parsed.data`
- Moved code out of `then` block
> fix: edit some faulty tests

- src/InboundServer/index.js
- src/InboundServer/middlewares.js
- src/OutboundServer/index.js
- src/OutboundServer/middlewares.js
- src/TestServer/index.js
- src/lib/metrics.js
- src/lib/router.js
- src/lib/validate.js
make logs less verbose when idling
> feat: suppress health check logs

- .circleci/config.yml
- package-lock.json
- package.json
- src/index.js
Fix creating InboundServer object
> fix: creating inbound server

- .npmignore
- audit-resolve.json
This is to fix Image Scans picking up unnecessary `test/data` folder in the Unit/Integration tests which contain dummy keys, ref: https://app.circleci.com/pipelines/github/mojaloop/simulator/215/workflows/56f815aa-b521-4a20-b43e-ee8edc9cb6da/jobs/1862
> chore: added .npmignore so that the test folder is not included when publishing packages

- audit-ci.jsonc
- modules/outbound-command-event-handler/src/domain/bulk_transaction_agg/handlers/process_party_info_callback.ts
- modules/outbound-command-event-handler/src/domain/bulk_transaction_agg/index.ts
- modules/outbound-command-event-handler/src/infrastructure/inmemory_bulk_transaction_repo.ts
- modules/outbound-domain-event-handler/src/application/handler.ts
- modules/outbound-domain-event-handler/src/application/handlers/index.ts
- modules/outbound-domain-event-handler/src/application/handlers/sdk-outbound-bulk-party-info-requested.ts
- modules/outbound-domain-event-handler/test/unit/application/handlers/sdk-outbound-bulk-party-info-requested.test.ts
- modules/private-shared-lib/src/events/outbound_domain_event_message/index.ts
- modules/private-shared-lib/src/events/outbound_domain_event_message/party_info_callback_processed.ts
- modules/private-shared-lib/src/events/outbound_domain_event_message/party_info_requested.ts
- modules/private-shared-lib/src/events/outbound_domain_event_message/sdk_outbound_bulk_party_info_requested.ts
- modules/private-shared-lib/src/events/outbound_domain_event_message/sdk_outbound_bulk_request_received.ts
feat(mojaloop/#2883): add SDKOutboundBulkPartyInfoRequested handler - [https://github.com/mojaloop/project/issues/2883](https://github.com/mojaloop/project/issues/2883)
- Rename PartyInfoCallbackProceededMessage to PartyInfoCallbackProcessedMessage as outlined by https://github.com/mojaloop/sdk-scheme-adapter/blob/mvp/bulk-sdk/docs/design-bulk-transfers/outbound-sequence.md
- Add SDKOutboundBulkPartyInfoRequested domain event handler
> feat(mojaloop/#2883): add SDKOutboundBulkPartyInfoRequested domain event handler

- modules/api-svc/package.json
- modules/outbound-command-event-handler/package.json
- modules/outbound-command-event-handler/src/domain/bulk_transaction_agg/handlers/process_party_info_callback.ts
- modules/outbound-domain-event-handler/package.json
- modules/private-shared-lib/package.json
- package.json
- yarn.lock
- Fix issue in party callback logic where a failed party lookup would not have `transactionId` set. Without it, a 400 would be thrown when the bulkTransaction callback is sent to the payer backend.
Should address in progress TC-BP2 test.
```
"errorInformation": {
"errorCode": "3100",
"errorDescription": "must have required property 'transactionId'",
"extensionList": [
{
"key": "keyword",
"value": "required"
},
{
"key": "instancePath",
"value": "/requestBody/individualTransferResults/0"
},
{
"key": "missingProperty",
"value": "transactionId"
}
]
}
},
```
> fix: update party callback handling

- modules/api-svc/src/InboundServer/handlers.js
- modules/api-svc/src/InboundServer/index.js
- modules/api-svc/src/OutboundServer/index.js
- modules/api-svc/src/TestServer/index.js
- modules/api-svc/src/index.js
- modules/api-svc/src/lib/router.js
- modules/api-svc/src/lib/validate.js
By setting the env variable MULTI_DFSP=true, we can handle multiple DFSPs with a single server. This saves resources when running multiple DFSPs and allows much bigger number of DFSPs to be handled without the need of extra configuration.
> feat: allow optional dfspId to be in the endpoint path
